//
//  NSPasteboardType+NotchFun.swift
//  boringNotch
//
//  Adapted from Maccy (https://github.com/p0deje/Maccy)
//  Source: Maccy/Extensions/NSPasteboard.PasteboardType+Types.swift
//  MIT License © Alex Rodionov. See THIRD_PARTY_LICENSES.
//

import AppKit.NSPasteboard

extension NSPasteboard.PasteboardType {
    static let heic = NSPasteboard.PasteboardType(rawValue: "public.heic")
    static let jpeg = NSPasteboard.PasteboardType(rawValue: "public.jpeg")
    static let utf8PlainText = NSPasteboard.PasteboardType(rawValue: "public.utf8-plain-text")
    static let webArchive = NSPasteboard.PasteboardType(rawValue: "com.apple.webarchive")

    /// Universal Clipboard (Handoff) marker.
    static let universalClipboard = NSPasteboard.PasteboardType(rawValue: "com.apple.is-remote-clipboard")

    // The nspasteboard.org convention. Password managers and other privacy-sensitive
    // apps mark their copies with these so clipboard managers skip them.
    // See http://nspasteboard.org for details.
    static let autoGenerated = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")
    static let concealed = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.ConcealedType")
    static let source = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.source")
    static let transient = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")

    /// Set by text-transforming tools to signal "same clip, modified".
    /// https://github.com/p0deje/Maccy/issues/429#issuecomment-1182575226
    static let modified = NSPasteboard.PasteboardType(rawValue: "x.nspasteboard.ModifiedType")

    /// Marks that the copy was made by NotchFun itself, so the monitor can
    /// ignore its own writes instead of re-recording them on the next poll.
    static let fromNotchFun = NSPasteboard.PasteboardType(rawValue: "io.github.lookatsarthak.notchfun")

    // Microsoft Word bookmarks (links).
    static let microsoftObjectLink = NSPasteboard.PasteboardType(rawValue: "com.microsoft.ObjectLink")
    static let microsoftLinkSource = NSPasteboard.PasteboardType(rawValue: "com.microsoft.Link-Source")

    // Safari preview and extra metadata that changes on every copy of the same content.
    static let linkPresentationMetadata = NSPasteboard.PasteboardType(rawValue: "com.apple.linkpresentation.metadata")
    static let customWebKitPasteboardData = NSPasteboard.PasteboardType(rawValue: "com.apple.WebKit.custom-pasteboard-data")

    // Chromium-based apps (Chrome, Edge, VS Code).
    static let customChromiumWebData = NSPasteboard.PasteboardType(rawValue: "org.chromium.web-custom-data")
    static let chromiumSourceUrl = NSPasteboard.PasteboardType(rawValue: "org.chromium.source-url")
    static let chromiumSourceToken = NSPasteboard.PasteboardType(rawValue: "org.chromium.internal.source-rfh-token")

    // Apple Notes.
    static let notesRichText = NSPasteboard.PasteboardType(rawValue: "com.apple.notes.richtext")
}

// MARK: - Type groups

enum ClipboardPasteboardTypes {
    /// Types NotchFun knows how to store and re-paste.
    static let supported: Set<NSPasteboard.PasteboardType> = [
        .fileURL, .html, .png, .rtf, .string, .tiff
    ]

    /// Presence of any of these means the copy must never be recorded.
    /// This is the password-manager safety net.
    static let ignored: Set<NSPasteboard.PasteboardType> = [
        .autoGenerated, .concealed, .transient
    ]

    /// Legacy password-manager types that predate the nspasteboard.org convention.
    static let ignoredRawValues: Set<String> = [
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb"
    ]

    /// Image types, most-preferred first.
    static let image: [NSPasteboard.PasteboardType] = [.png, .tiff, .jpeg, .heic]

    /// Types excluded when comparing two clips for equality. These change on every
    /// copy of the same content, so including them would defeat deduplication.
    static let transientForComparison: Set<String> = [
        NSPasteboard.PasteboardType.fromNotchFun.rawValue,
        NSPasteboard.PasteboardType.source.rawValue,
        NSPasteboard.PasteboardType.modified.rawValue,
        NSPasteboard.PasteboardType.linkPresentationMetadata.rawValue,
        NSPasteboard.PasteboardType.customWebKitPasteboardData.rawValue,
        NSPasteboard.PasteboardType.customChromiumWebData.rawValue,
        NSPasteboard.PasteboardType.chromiumSourceUrl.rawValue,
        NSPasteboard.PasteboardType.chromiumSourceToken.rawValue,
        NSPasteboard.PasteboardType.notesRichText.rawValue
    ]

    /// Dynamic UTIs, which are per-launch and meaningless to persist.
    static let dynamicPrefix = "dyn."
    /// Microsoft Office writes a unique source id on every copy.
    static let microsoftSourcePrefix = "com.microsoft.ole.source."

    static func isNoise(_ rawValue: String) -> Bool {
        rawValue.hasPrefix(dynamicPrefix) || rawValue.hasPrefix(microsoftSourcePrefix)
    }
}
